name: CI

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff
        run: |
          docker plugin install grafana/loki-docker-driver:2.9.4 --alias loki --grant-all-permissions
          docker compose -f deployments/dev/docker-compose.yaml run backend ruff check src

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mypy
        run: |
          docker plugin install grafana/loki-docker-driver:2.9.4 --alias loki --grant-all-permissions
          docker compose -f deployments/dev/docker-compose.yaml run backend mypy src
